### PR TITLE
Change definition to close Issue #106

### PR DESCRIPTION
**Pull request by jhdalek55**
Modify ECU identifier  definition as "a globally unique attribute....'  Closes Issue #106

### CODE REVIEW

**Comment by jhdalek55** [comment]
After discussing this issue in the 5/25 Standards meeting, we decided to leave the definition as is, and add a qualifying sentence that adds a "should" element.

**Comment by jhdalek55** [comment]
I amended the statement as per above.

**Comment by jhdalek55** [comment]
Can I get an approval on this so we can merge it?

**Review by mnm678 — APPROVED** [review]
Looks good!

**Pull request merged**
