### PR TITLE
Changing the changelog

### PR DESCRIPTION
**Pull request by jhdalek55**
I used the link @plapczyn provided in Issue #89 to edit and reformat the Changelog. This now should fit the stipulations in that document. The one thing I was unsure about was how in-depth  the "Unreleased" section should be. The document said it should list issues/changes not yet released. We current have over 20 such issues, including some we know may not be addressed promptly. Perhaps @plapczyn and.or @iramcdonald can provide input and advice. @tkfu this revised changelog would need to be included in your proposed Deployment Best Practices document.

### CODE REVIEW

**Comment by pattivacek** [comment]
I don't think open issues should be put in the changelog. I think the unreleased section is for changes that have been made since the last release.

**Comment by iramcdonald** [comment]
Hi,

I agree with Patti.  However some other documents may use this Change Log
format,
I want to stress that the IETF, who have championed this "changes since the
previous
version" section, have never allowed the inclusion of any speculative info
(e.g., "we
hope to add this feature, changing x and y current text") into their change
logs.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
@pattivacek, I would prefer not to list open issues. Either I misread the document I used for guidance, or it just wasn't clear. I am going to remove that list.

**Review by pattivacek — APPROVED** [review]

**Comment by jhdalek55** [comment]
@iramcdonald After reading your note, I checked and with the open issue list removed, I don't think the "changelog" listings include any "speculative info." Ok with you if I merge so we can get this posted?

**Comment by iramcdonald** [comment]
Hi Lois,

Yes please merge.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Thanks, all. Merging now.

**Pull request merged**
