### PR TITLE
Glossary changes based on @pattivacek comments--addresses Issue #83

### PR DESCRIPTION
**Pull request by jhdalek55**
I had added text to the glossary based on comments @pattivacek  made on an earlier draft of this PR (which I accidentally merged directly).   I am opening this PR in part to act on those suggestions, and also to solicit changes based on a more fundamental question raised by @pattivacek. I am particularly directing this to @iramcdonald, but others are welcomed to chime in.

 What appears here is essentially the same glossary as in the Standard. I have not included the explanation of  Conformance Terminology, as these pages use much less of it than the Standard, and @pattivacek noted that none of the acronyms in that list appear in the Deployment pages. I also eliminated  some one-sentence introductory text that didn't feel needed in this context.  Is this what we need for such a section in Deployment Best Practices? Or do we need to evolve new terminology for this document? Perhaps we need to cull the pages.

I would appreciate your thoughts, as well as those of others on the team.

### CODE REVIEW

**Comment by jhdalek55** [comment]
If we follow-upon the suggestion of  @iramcdonald we would need to remove the existing glossary in the Standard and replace the elements we removed here. If we have consensus here to make this move I will open a new PR in the Standard to remove the glossary there. I still think, as suggested above, that we should skim for other terms unique to deployment, if any.

**Comment by jhdalek55** [comment]
To administer @iramcdonald's recommendation to move the glossary from the Standard to the Deployment pages we need to remove the text all under terminology from the main file and then replace it with a pointer towards the Deployment "Glossary" pages. While I could do the edit, I'm not sure about setting up the pointer. Could someone take care of this? Meanwhile I am going to ensure the full glossary is set up as some text was removed when I thought this would a duplicate of the page in the Standard.

**Comment by jhdalek55** [comment]
I need an approval and I can close this PR.

**Review by mnm678 — APPROVED** [review]

**Comment by jhdalek55** [comment]
Thanks, Marina.

**Pull request merged**
